<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="discussion" nsURI="http://www.symo4pd.de/discussion/2016/" nsPrefix="dis">
  <eClassifiers xsi:type="ecore:EClass" name="Note">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Discribes a notification. The notification includes a message text the author and the date of origin."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Note" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Discussion" eSuperTypes="SYMO_Base.ecore#//ADataItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subject" eType="ecore:EClass SYMO_Base.ecore#//ADataItem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="notes" upperBound="-1"
        eType="#//Note"/>
  </eClassifiers>
</ecore:EPackage>
