<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="registry" nsURI="http://www.symo4pd.de/registry/2016/" nsPrefix="reg">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="The package registry contains all model elements to the description of lists of global definitions. These may be, for example, units and constants."/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore"/>
  <eClassifiers xsi:type="ecore:EClass" name="Registry" eSuperTypes="SYMO_Base.ecore#//ANameItem SYMO_Base.ecore#//AVersionedModelRoot">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The registry contains lists of global definitions of disciplines, units, constants."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="units" upperBound="-1"
        eType="#//Measurement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constants" upperBound="-1"
        eType="#//Constant" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stereotypes" upperBound="-1"
        eType="ecore:EClass SYMO_Base.ecore#//Stereotype" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="ecore:EClass SYMO_Base.ecore#//Parameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnitRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conversionFactor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetUnit" lowerBound="1"
        eType="ecore:EClass SYMO_Base.ecore#//Unit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Measurement" eSuperTypes="SYMO_Base.ecore#//Unit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="unitRef" upperBound="-1"
        eType="#//UnitRef" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constant" eSuperTypes="SYMO_Base.ecore#//AParameterDef">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A constant defines a constant value of a system element like a physical constant."/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
