<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://symo4pd/toolchain/docgen/model" nsPrefix="symo4pd.toolchain.docgen.model">
  <eClassifiers xsi:type="ecore:EClass" name="DocModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Namespace"/>
  </eClassifiers>
</ecore:EPackage>
